CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL,
  name TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL, email_verified_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS memories (
  id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL, caption TEXT NOT NULL DEFAULT '', place TEXT NOT NULL DEFAULT '',
  date DATE NOT NULL, media_url TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_memories_user_date ON memories(user_id,date DESC,created_at DESC);
CREATE TABLE IF NOT EXISTS profiles (
  user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, bio TEXT DEFAULT '', avatar_url TEXT DEFAULT '',
  timezone TEXT DEFAULT 'UTC', privacy TEXT DEFAULT 'private', updated_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT UNIQUE NOT NULL, device TEXT DEFAULT '', created_at TIMESTAMPTZ NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL, revoked_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE TABLE IF NOT EXISTS memory_meta (
  memory_id TEXT PRIMARY KEY REFERENCES memories(id) ON DELETE CASCADE, time TEXT, timezone TEXT,
  lat DOUBLE PRECISION, lng DOUBLE PRECISION, address TEXT, category TEXT DEFAULT 'memory', mood TEXT,
  favorite BOOLEAN DEFAULT FALSE, pinned BOOLEAN DEFAULT FALSE, deleted_at TIMESTAMPTZ,
  source TEXT DEFAULT 'manual', summary TEXT DEFAULT '', weather TEXT
);
CREATE TABLE IF NOT EXISTS media (
  id TEXT PRIMARY KEY, memory_id TEXT REFERENCES memories(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  original_name TEXT NOT NULL, mime_type TEXT NOT NULL, size BIGINT NOT NULL, storage_path TEXT NOT NULL,
  checksum TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL, status TEXT NOT NULL DEFAULT 'ready'
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_media_user_checksum ON media(user_id,checksum);
CREATE TABLE IF NOT EXISTS tags (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,UNIQUE(user_id,name));
CREATE TABLE IF NOT EXISTS memory_tags (memory_id TEXT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,tag_id TEXT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,PRIMARY KEY(memory_id,tag_id));
CREATE TABLE IF NOT EXISTS people (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,UNIQUE(user_id,name));
CREATE TABLE IF NOT EXISTS memory_people (memory_id TEXT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,person_id TEXT NOT NULL REFERENCES people(id) ON DELETE CASCADE,PRIMARY KEY(memory_id,person_id));
CREATE TABLE IF NOT EXISTS locations (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,lat DOUBLE PRECISION,lng DOUBLE PRECISION,address TEXT,UNIQUE(user_id,name));
CREATE TABLE IF NOT EXISTS memory_locations (memory_id TEXT PRIMARY KEY REFERENCES memories(id) ON DELETE CASCADE,location_id TEXT NOT NULL REFERENCES locations(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS shares (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,token TEXT UNIQUE NOT NULL,title TEXT DEFAULT '',visibility TEXT DEFAULT 'private',password_hash TEXT,expires_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL,revoked_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS share_items (share_id TEXT NOT NULL REFERENCES shares(id) ON DELETE CASCADE,memory_id TEXT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,PRIMARY KEY(share_id,memory_id));
CREATE TABLE IF NOT EXISTS collaborators (memory_id TEXT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,owner_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,user_email TEXT NOT NULL,role TEXT DEFAULT 'viewer',status TEXT DEFAULT 'invited',created_at TIMESTAMPTZ NOT NULL,PRIMARY KEY(memory_id,user_email));
CREATE TABLE IF NOT EXISTS comments (id TEXT PRIMARY KEY,memory_id TEXT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,body TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS reactions (memory_id TEXT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,reaction TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL,PRIMARY KEY(memory_id,user_id));
CREATE TABLE IF NOT EXISTS calendar_events (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,title TEXT NOT NULL,start_at TIMESTAMPTZ NOT NULL,end_at TIMESTAMPTZ,notes TEXT DEFAULT '',memory_id TEXT,created_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS notifications (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,type TEXT NOT NULL,title TEXT NOT NULL,body TEXT DEFAULT '',read_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS ai_jobs (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,type TEXT NOT NULL,status TEXT DEFAULT 'pending',input_json JSONB,output_json JSONB,error TEXT,created_at TIMESTAMPTZ NOT NULL,completed_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS embeddings (memory_id TEXT PRIMARY KEY REFERENCES memories(id) ON DELETE CASCADE,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,text TEXT NOT NULL,vector vector(1536),created_at TIMESTAMPTZ NOT NULL);
CREATE INDEX IF NOT EXISTS idx_embeddings_vector ON embeddings USING hnsw (vector vector_cosine_ops);
CREATE TABLE IF NOT EXISTS replays (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,title TEXT NOT NULL,period_start DATE,period_end DATE,status TEXT DEFAULT 'ready',narrative TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS audit_logs (id TEXT PRIMARY KEY,user_id TEXT,action TEXT NOT NULL,resource_type TEXT,resource_id TEXT,metadata JSONB,created_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS account_tokens (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,type TEXT NOT NULL,token_hash TEXT UNIQUE NOT NULL,expires_at TIMESTAMPTZ NOT NULL,consumed_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL);
CREATE INDEX IF NOT EXISTS idx_account_tokens ON account_tokens(user_id,type,expires_at);
CREATE TABLE IF NOT EXISTS integrations (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,provider TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active',encrypted_access_token BYTEA,encrypted_refresh_token BYTEA,expires_at TIMESTAMPTZ,scopes TEXT,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL,UNIQUE(user_id,provider));
CREATE TABLE IF NOT EXISTS import_jobs (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,provider TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'queued',cursor TEXT,processed_count INTEGER DEFAULT 0,error TEXT,created_at TIMESTAMPTZ NOT NULL,completed_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS webhook_events (id TEXT PRIMARY KEY,provider TEXT NOT NULL,event_key TEXT UNIQUE NOT NULL,payload JSONB NOT NULL,received_at TIMESTAMPTZ NOT NULL,processed_at TIMESTAMPTZ,error TEXT);
