const KEY='life-replay.memories.v2', SESSION='life-replay.session.v1';
const seed=[
{id:1,date:'2026-01-01',title:'A new beginning',caption:'New year, new energy.',place:'Home',src:'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=1200&q=85'},
{id:2,date:'2026-02-14',title:'Small moments',caption:'The moments worth keeping.',place:'City',src:'https://images.unsplash.com/photo-1511988617509-a57c8a288659?auto=format&fit=crop&w=1200&q=85'},
{id:3,date:'2026-03-21',title:'Out there',caption:'A day that felt different.',place:'Travel',src:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=85'}
];
let session=loadSession(),memories=[],mode='home',query='',placeFilter='all',loading=false;
const $=s=>document.querySelector(s);
const fmt=d=>new Date(d+'T00:00:00').toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'});
const month=d=>new Date(d+'T00:00:00').toLocaleString(undefined,{month:'long'});
function loadSession(){try{return JSON.parse(localStorage.getItem(SESSION))||null}catch{return null}}
function saveSession(x){session=x;localStorage.setItem(SESSION,JSON.stringify(x))}
function clearSession(){session=null;localStorage.removeItem(SESSION)}
function loadLocal(){try{const x=JSON.parse(localStorage.getItem(KEY));return Array.isArray(x)?x:seed.map(x=>({...x}))}catch{return seed.map(x=>({...x}))}}
function saveLocal(){localStorage.setItem(KEY,JSON.stringify(memories))}
async function api(path,options={}){const headers={...(options.headers||{})};if(session?.token)headers.Authorization=`Bearer ${session.token}`;const r=await fetch(path,{...options,headers});let body=null;try{body=await r.json()}catch{}if(r.status===401&&session){clearSession();throw Error('Your session expired. Please sign in again.')}if(!r.ok)throw Error(body?.error||`Request failed (${r.status})`);return body}
async function loadMemories(){const shareMatch=location.pathname.match(/^\/share\/([^/]+)\/?$/);if(shareMatch){loading=true;renderHome();try{const data=await api(`/api/share/${encodeURIComponent(shareMatch[1])}`);memories=(data.memories||[]).map(m=>({...m,src:m.mediaUrl}));mode='story';renderStory()}catch(e){memories=[];mode='story';$('#app').innerHTML=`<div class="story"><section class="storyIntro"><div class="eyebrow">✦ LIFE REPLAY</div><h1>Story unavailable.</h1><p>${esc(e.message)}</p><button class="primary" onclick="history.pushState({},'', '/');location.reload()">Go to Life Replay</button></section></div>`}finally{loading=false}return}if(!session){memories=loadLocal();return}loading=true;renderHome();try{const data=await api('/api/memories');memories=(data.memories||[]).map(m=>({...m,src:m.mediaUrl}));}catch(e){toast(e.message)}finally{loading=false;renderHome()}}
function stats(){return{places:new Set(memories.map(x=>x.place)).size,years:new Set(memories.map(x=>new Date(x.date).getFullYear())).size,photos:memories.length}}
function visible(){return memories.filter(m=>(!query||`${m.title} ${m.caption} ${m.place}`.toLowerCase().includes(query.toLowerCase()))&&(placeFilter==='all'||m.place===placeFilter))}
function header(){return `<header class="header"><div class="brand" onclick="mode='home';query='';render()"><span class="mark">✦</span>life replay</div><div class="headerActions"><button class="ghost" onclick="shareStory()">↗ Share</button>${session?`<button class="ghost" onclick="logout()">Sign out</button>`:`<button class="ghost" onclick="openAuth('login')">Sign in</button>`}<button class="ghost" onclick="exportData()">Export</button></div></header>`}
function render(){mode==='story'?renderStory():renderHome()}
function renderHome(){const list=visible();let grouped={};list.forEach(m=>(grouped[new Date(m.date).getFullYear()]??=[]).push(m));const s=stats();const places=[...new Set(memories.map(m=>m.place))].sort();let timeline=Object.entries(grouped).sort((a,b)=>b[0]-a[0]).map(([y,items])=>`<div class="year"><div class="yearLabel">${y}</div><div class="rail">${items.sort((a,b)=>a.date.localeCompare(b.date)).map(m=>`<article class="memory" onclick="openMemory('${String(m.id).replace(/'/g,"\\'")}')"><i class="dot"></i><div class="date">${month(m.date).toUpperCase()} · ${new Date(m.date).getDate()}</div><div class="card"><img src="${esc(m.src)}" alt="${esc(m.title)}" loading="lazy"><div class="body"><h3>${esc(m.title)}</h3><p>${esc(m.caption)}</p><div class="meta"><span>⌖ ${esc(m.place)}</span><span>♡</span></div></div></div></article>`).join('')}</div></div>`).join('');if(!timeline)timeline=`<div class="empty">${loading?'Loading your memories…':'No memories match this view.'}</div>`;
$('#app').innerHTML=`<div class="app">${header()}<main><section class="hero"><div class="eyebrow">✦ YOUR LIFE, REIMAGINED</div><h1>Turn your life<br><em>into a story.</em></h1><p>${session?'Your private memories are synced to your account.':'Keep the moments that matter in one private timeline. Sign in to keep them across devices.'}</p><div class="actions"><button class="primary" onclick="fileInput.click()">＋ Add memories</button><button class="secondary" onclick="mode='story';render()">▶ Replay my year</button></div><input id="fileInput" hidden type="file" accept="image/*" multiple></section><section class="stats"><div><b>${s.photos}</b><span>memories</span></div><div><b>${s.places}</b><span>places</span></div><div><b>${s.years}</b><span>years</span></div><div><b>∞</b><span>stories</span></div></section><section class="tools"><input id="search" placeholder="Search memories…" value="${esc(query)}"><select id="place"><option value="all">All places</option>${places.map(p=>`<option ${p===placeFilter?'selected':''}>${esc(p)}</option>`).join('')}</select><label class="importBtn">Import<input hidden type="file" id="importFile" accept="application/json"></label></section><section class="sectionHead"><div><div class="eyebrow">YOUR TIMELINE</div><h2>Moments that matter</h2></div><button class="add" onclick="fileInput.click()">＋</button></section><section class="timeline">${timeline}</section><section class="cta"><div class="eyebrow">✦ KEEP GOING</div><h2>There are more stories<br>waiting to be remembered.</h2><button class="primary" onclick="fileInput.click()">Add another memory →</button></section></main></div>`;
$('#fileInput').addEventListener('change',handleFiles);$('#search').addEventListener('input',e=>{query=e.target.value;renderHome()});$('#place').addEventListener('change',e=>{placeFilter=e.target.value;renderHome()});$('#importFile').addEventListener('change',importData)}
function renderStory(){const s=stats();$('#app').innerHTML=`<div class="story"><button class="back" onclick="location.href='/'">← Back to Life Replay</button><section class="storyIntro"><div class="eyebrow">✦ YOUR REPLAY</div><h1>One year.<br><em>So many moments.</em></h1><p>${memories.length} memories across ${s.places} places. Here's the story so far.</p>${session?`<button class="primary" onclick="shareStory()">↗ Share story</button>`:''}</section><section class="storyGrid">${memories.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(m=>`<article class="storyItem"><img src="${esc(m.src)}" alt="${esc(m.title)}" loading="lazy"><div><small>${fmt(m.date)} · ${esc(m.place)}</small><h3>${esc(m.title)}</h3><p>${esc(m.caption)}</p></div></article>`).join('')}</section><footer>life replay · your memories, your story.</footer></div>`}
async function handleFiles(e){const files=[...e.target.files].filter(f=>f.type.startsWith('image/'));for(const f of files){try{if(session){const fd=new FormData();fd.append('image',f);fd.append('title',f.name.replace(/\.[^.]+$/,'').replace(/[-_]+/g,' ')||'A moment worth remembering');fd.append('caption','Captured and kept.');fd.append('place','My memories');fd.append('date',new Date(f.lastModified||Date.now()).toISOString().slice(0,10));await api('/api/memories',{method:'POST',body:fd});}else{await new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>{memories.unshift({id:Date.now()+Math.random(),date:new Date(f.lastModified||Date.now()).toISOString().slice(0,10),title:f.name.replace(/\.[^.]+$/,'').replace(/[-_]+/g,' ')||'A moment worth remembering',caption:'Captured and kept.',place:'My memories',src:reader.result,type:f.type});saveLocal();resolve()};reader.readAsDataURL(f)})}toast('Memory added to your replay ✦')}catch(err){toast(err.message);break}}e.target.value='';await loadMemories();render()}
function openMemory(id){const m=memories.find(x=>String(x.id)===String(id));if(!m)return;$('#app').insertAdjacentHTML('beforeend',`<div class="modal" id="modal" onclick="closeModal()"><div class="modalBox" onclick="event.stopPropagation()"><button class="close" onclick="closeModal()">×</button><img src="${esc(m.src)}" alt="${esc(m.title)}"><div class="modalContent"><small>${fmt(m.date)} · ${esc(m.place)}</small><h2>${esc(m.title)}</h2><p>${esc(m.caption)}</p>${session?`<button class="danger" onclick="removeMemory('${String(m.id).replace(/'/g,"\\'")}')">Remove memory</button>`:''}</div></div></div>`)}
function closeModal(){$('#modal')?.remove()}
async function removeMemory(id){try{if(session)await api(`/api/memories/${encodeURIComponent(id)}`,{method:'DELETE'});memories=memories.filter(m=>String(m.id)!==String(id));if(!session)saveLocal();closeModal();render();toast('Memory removed')}catch(e){toast(e.message)}}
async function shareStory(){try{if(session){const x=await api('/api/share',{method:'POST'});const url=x.url;if(navigator.share)await navigator.share({title:'My Life Replay',text:`My Life Replay — ${memories.length} memories across ${stats().places} places.`,url});else await navigator.clipboard?.writeText(url),toast('Private story link copied');return}const payload=btoa(unescape(encodeURIComponent(JSON.stringify(memories.map(({id,date,title,caption,place})=>({id,date,title,caption,place}))))));const url=`${location.origin}${location.pathname}#replay=${payload}`;if(navigator.share)navigator.share({title:'My Life Replay',text:`My Life Replay — ${memories.length} memories across ${stats().places} places.`,url}).catch(()=>{});else navigator.clipboard?.writeText(url).then(()=>toast('Share link copied')).catch(()=>toast('Use the browser share menu'))}catch(e){toast(e.message)}}
function exportData(){const blob=new Blob([JSON.stringify(memories,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='life-replay-memories.json';a.click();URL.revokeObjectURL(a.href);toast('Backup downloaded')}
function importData(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!Array.isArray(x))throw Error();memories=x.filter(m=>m&&m.date&&m.src).map(m=>({...m,id:m.id||Date.now()+Math.random()}));saveLocal();render();toast('Memories restored locally. Sign in to sync across devices.')}catch{toast('Invalid backup file')}};r.readAsText(f);e.target.value=''}
function openAuth(kind='login'){const register=kind==='register';$('#app').insertAdjacentHTML('beforeend',`<div class="modal" id="authModal" onclick="closeAuth()"><div class="modalBox authBox" onclick="event.stopPropagation()"><button class="close" onclick="closeAuth()">×</button><div class="modalContent"><div class="eyebrow">✦ LIFE REPLAY</div><h2>${register?'Create your account':'Welcome back'}</h2><p>${register?'Keep your memories private and available across devices.':'Sign in to continue your private replay.'}</p><form id="authForm"><input id="authName" ${register?'':'hidden'} placeholder="Your name" autocomplete="name"><input id="authEmail" type="email" placeholder="Email" autocomplete="email" required><input id="authPassword" type="password" placeholder="Password (8+ characters)" minlength="8" autocomplete="${register?'new-password':'current-password'}" required><button class="primary" type="submit">${register?'Create account':'Sign in'}</button></form><button class="ghost" onclick="openAuth('${register?'login':'register'}')">${register?'Already have an account? Sign in':'New here? Create a free account'}</button></div></div></div>`);$('#authForm').addEventListener('submit',e=>submitAuth(e,register))}
function closeAuth(){$('#authModal')?.remove()}
async function submitAuth(e,register){e.preventDefault();const body={email:$('#authEmail').value,password:$('#authPassword').value};if(register)body.name=$('#authName').value.trim();try{const data=await api(`/api/auth/${register?'register':'login'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});saveSession({token:data.token,user:data.user});closeAuth();await loadMemories();render();toast(register?'Account created ✦':'Welcome back ✦')}catch(err){toast(err.message)}}
function logout(){clearSession();memories=loadLocal();mode='home';render();toast('Signed out safely')}
function restoreShared(){const h=location.hash;if(!h.startsWith('#replay='))return;try{const x=JSON.parse(decodeURIComponent(escape(atob(h.slice(8)))));if(Array.isArray(x)&&x.length){memories=x.map(m=>({...m,src:placeholder(m.place)}));mode='story';toast('Shared replay opened (photos are private)')}}catch{}}
function placeholder(){return 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=85'}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2600)}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
restoreShared();loadMemories().then(render);
