const KEY='life-replay.memories.v2';
const seed=[
{id:1,date:'2026-01-01',title:'A new beginning',caption:'New year, new energy.',place:'Home',src:'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=1200&q=85'},
{id:2,date:'2026-02-14',title:'Small moments',caption:'The moments worth keeping.',place:'City',src:'https://images.unsplash.com/photo-1511988617509-a57c8a288659?auto=format&fit=crop&w=1200&q=85'},
{id:3,date:'2026-03-21',title:'Out there',caption:'A day that felt different.',place:'Travel',src:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=85'}
];
let memories=load(),mode='home',query='',placeFilter='all';
const $=s=>document.querySelector(s);
const fmt=d=>new Date(d+'T00:00:00').toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'});
const month=d=>new Date(d+'T00:00:00').toLocaleString(undefined,{month:'long'});
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return Array.isArray(x)?x:seed.map(x=>({...x}));}catch{return seed.map(x=>({...x}))}}
function save(){localStorage.setItem(KEY,JSON.stringify(memories));}
function stats(){return{places:new Set(memories.map(x=>x.place)).size,years:new Set(memories.map(x=>new Date(x.date).getFullYear())).size,photos:memories.filter(x=>x.type?.startsWith('image/')||!x.type).length}}
function visible(){return memories.filter(m=>(!query||`${m.title} ${m.caption} ${m.place}`.toLowerCase().includes(query.toLowerCase()))&&(placeFilter==='all'||m.place===placeFilter))}
function header(){return `<header class="header"><div class="brand" onclick="mode='home';query='';render()"><span class="mark">✦</span>life replay</div><div class="headerActions"><button class="ghost" onclick="shareStory()">↗ Share</button><button class="ghost" onclick="exportData()">Export</button></div></header>`}
function render(){mode==='story'?renderStory():renderHome()}
function renderHome(){const list=visible();let grouped={};list.forEach(m=>(grouped[new Date(m.date).getFullYear()]??=[]).push(m));const s=stats();const places=[...new Set(memories.map(m=>m.place))].sort();let timeline=Object.entries(grouped).sort((a,b)=>b[0]-a[0]).map(([y,items])=>`<div class="year"><div class="yearLabel">${y}</div><div class="rail">${items.sort((a,b)=>a.date.localeCompare(b.date)).map(m=>`<article class="memory" onclick="openMemory(${m.id})"><i class="dot"></i><div class="date">${month(m.date).toUpperCase()} · ${new Date(m.date).getDate()}</div><div class="card"><img src="${m.src}" alt="${esc(m.title)}" loading="lazy"><div class="body"><h3>${esc(m.title)}</h3><p>${esc(m.caption)}</p><div class="meta"><span>⌖ ${esc(m.place)}</span><span>♡</span></div></div></div></article>`).join('')}</div></div>`).join('');if(!timeline)timeline='<div class="empty">No memories match this view.</div>';
$('#app').innerHTML=`<div class="app">${header()}<main><section class="hero"><div class="eyebrow">✦ YOUR LIFE, REIMAGINED</div><h1>Turn your life<br><em>into a story.</em></h1><p>Keep the moments that matter in one private timeline. Your memories stay in this browser until you choose to export or share them.</p><div class="actions"><button class="primary" onclick="fileInput.click()">＋ Add memories</button><button class="secondary" onclick="mode='story';render()">▶ Replay my year</button></div><input id="fileInput" hidden type="file" accept="image/*" multiple></section><section class="stats"><div><b>${s.photos}</b><span>memories</span></div><div><b>${s.places}</b><span>places</span></div><div><b>${s.years}</b><span>years</span></div><div><b>∞</b><span>stories</span></div></section><section class="tools"><input id="search" placeholder="Search memories…" value="${esc(query)}"><select id="place"><option value="all">All places</option>${places.map(p=>`<option ${p===placeFilter?'selected':''}>${esc(p)}</option>`).join('')}</select><label class="importBtn">Import<input hidden type="file" id="importFile" accept="application/json"></label></section><section class="sectionHead"><div><div class="eyebrow">YOUR TIMELINE</div><h2>Moments that matter</h2></div><button class="add" onclick="fileInput.click()">＋</button></section><section class="timeline">${timeline}</section><section class="cta"><div class="eyebrow">✦ KEEP GOING</div><h2>There are more stories<br>waiting to be remembered.</h2><button class="primary" onclick="fileInput.click()">Add another memory →</button></section></main></div>`;
$('#fileInput').addEventListener('change',handleFiles);$('#search').addEventListener('input',e=>{query=e.target.value;renderHome()});$('#place').addEventListener('change',e=>{placeFilter=e.target.value;renderHome()});$('#importFile').addEventListener('change',importData)}
function renderStory(){const s=stats();$('#app').innerHTML=`<div class="story"><button class="back" onclick="mode='home';render()">← Back to timeline</button><section class="storyIntro"><div class="eyebrow">✦ YOUR REPLAY</div><h1>One year.<br><em>So many moments.</em></h1><p>${memories.length} memories across ${s.places} places. Here's your story so far.</p><button class="primary" onclick="shareStory()">↗ Share story</button></section><section class="storyGrid">${memories.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(m=>`<article class="storyItem"><img src="${m.src}" alt="${esc(m.title)}" loading="lazy"><div><small>${fmt(m.date)} · ${esc(m.place)}</small><h3>${esc(m.title)}</h3><p>${esc(m.caption)}</p></div></article>`).join('')}</section><footer>life replay · your memories, your story.</footer></div>`}
function handleFiles(e){[...e.target.files].forEach((f,i)=>{if(!f.type.startsWith('image/'))return;const reader=new FileReader();reader.onload=()=>{memories.unshift({id:Date.now()+i,date:new Date(f.lastModified||Date.now()).toISOString().slice(0,10),title:f.name.replace(/\.[^.]+$/,'').replace(/[-_]+/g,' ')||'A moment worth remembering',caption:'Captured and kept.',place:'My memories',src:reader.result,type:f.type});save();render();toast('Memory added to your replay ✦')};reader.readAsDataURL(f)});e.target.value=''}
function openMemory(id){const m=memories.find(x=>x.id===id);if(!m)return;$('#app').insertAdjacentHTML('beforeend',`<div class="modal" id="modal" onclick="closeModal()"><div class="modalBox" onclick="event.stopPropagation()"><button class="close" onclick="closeModal()">×</button><img src="${m.src}" alt="${esc(m.title)}"><div class="modalContent"><small>${fmt(m.date)} · ${esc(m.place)}</small><h2>${esc(m.title)}</h2><p>${esc(m.caption)}</p><button class="danger" onclick="removeMemory(${id})">Remove memory</button></div></div></div>`)}
function closeModal(){$('#modal')?.remove()}
function removeMemory(id){memories=memories.filter(m=>m.id!==id);save();closeModal();render();toast('Memory removed')}
function shareStory(){const payload=btoa(unescape(encodeURIComponent(JSON.stringify(memories.map(({id,date,title,caption,place})=>({id,date,title,caption,place}))))));const url=`${location.origin}${location.pathname}#replay=${payload}`;if(navigator.share)navigator.share({title:'My Life Replay',text:`My Life Replay — ${memories.length} memories across ${stats().places} places.`,url}).catch(()=>{});else navigator.clipboard?.writeText(url).then(()=>toast('Share link copied')).catch(()=>toast('Use the browser share menu'))}
function restoreShared(){const h=location.hash;if(!h.startsWith('#replay='))return;try{const x=JSON.parse(decodeURIComponent(escape(atob(h.slice(8)))));if(Array.isArray(x)&&x.length){memories=x.map(m=>({...m,src:placeholder(m.place)}));mode='story';toast('Shared replay opened (photos are private)')}}catch{}}
function placeholder(place){return `https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=85`}
function exportData(){const blob=new Blob([JSON.stringify(memories,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='life-replay-memories.json';a.click();URL.revokeObjectURL(a.href);toast('Backup downloaded')}
function importData(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!Array.isArray(x))throw Error();memories=x.filter(m=>m&&m.date&&m.src).map(m=>({...m,id:m.id||Date.now()+Math.random()}));save();render();toast('Memories restored')}catch{toast('Invalid backup file')}};r.readAsText(f);e.target.value=''}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2200)}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});restoreShared();render();
