const KEY='life-replay.memories.v3';
const SEED=[
 {id:1,date:'2026-01-01',title:'A new beginning',caption:'New year, new energy.',place:'Home',src:'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=1200&q=85'},
 {id:2,date:'2026-02-14',title:'Small moments',caption:'The moments worth keeping.',place:'City',src:'https://images.unsplash.com/photo-1511988617509-a57c8a288659?auto=format&fit=crop&w=1200&q=85'},
 {id:3,date:'2026-03-21',title:'Out there',caption:'A day that felt different.',place:'Travel',src:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=85'}
];
let memories=[],mode='home',query='',placeFilter='all';
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]})}
function load(){try{var raw=localStorage.getItem(KEY);var data=raw?JSON.parse(raw):null;return Array.isArray(data)?data:SEED.map(function(x){return Object.assign({},x)})}catch(e){return SEED.map(function(x){return Object.assign({},x)})}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(memories))}catch(e){}}
function fmtDate(d){return new Date(d+'T00:00:00').toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})}
function stats(){var places={};var years={};for(var i=0;i<memories.length;i++){places[memories[i].place]=1;years[new Date(memories[i].date).getFullYear()]=1}return{places:Object.keys(places).length,years:Object.keys(years).length,photos:memories.length}}
function visible(){var q=query.toLowerCase();return memories.filter(function(m){return(!q||((m.title||'')+' '+(m.caption||'')+' '+(m.place||'')).toLowerCase().indexOf(q)>=0)&&(placeFilter==='all'||m.place===placeFilter)})}
function header(){return '<header class="header"><div class="brand" onclick="goHome()"><span class="mark">✦</span>life replay</div><div class="headerActions"><button class="ghost" onclick="shareStory()">↗ Share</button><button class="ghost" onclick="exportData()">Export</button></div></header>'}
function goHome(){mode='home';query='';placeFilter='all';render()}
function render(){try{if(mode==='story')renderStory();else renderHome();if(window.clearLifeReplayBoot)window.clearLifeReplayBoot()}catch(e){showRuntimeError(e)}}
function renderHome(){var list=visible(),groups={},s=stats(),places=[];memories.forEach(function(m){if(places.indexOf(m.place)<0)places.push(m.place);var y=new Date(m.date).getFullYear();if(!groups[y])groups[y]=[];groups[y].push(m)});places.sort();var years=Object.keys(groups).sort(function(a,b){return Number(b)-Number(a)});var timeline='';years.forEach(function(y){var items=groups[y].slice().sort(function(a,b){return a.date.localeCompare(b.date)});var cards='';items.forEach(function(m){cards+='<article class="memory" onclick="openMemory('+Number(m.id)+')"><i class="dot"></i><div class="date">'+new Date(m.date+'T00:00:00').toLocaleString(undefined,{month:'long'}).toUpperCase()+' · '+new Date(m.date+'T00:00:00').getDate()+'</div><div class="card"><img src="'+esc(m.src)+'" alt="'+esc(m.title)+'" loading="lazy"><div class="body"><h3>'+esc(m.title)+'</h3><p>'+esc(m.caption)+'</p><div class="meta"><span>⌖ '+esc(m.place)+'</span><span>♡</span></div></div></div></article>'});timeline+='<div class="year"><div class="yearLabel">'+y+'</div><div class="rail">'+cards+'</div></div>'});if(!timeline)timeline='<div class="empty">No memories match this view.</div>';
document.getElementById('app').innerHTML='<div class="app">'+header()+'<main><section class="hero"><div class="eyebrow">✦ YOUR LIFE, REIMAGINED</div><h1>Turn your life<br><em>into a story.</em></h1><p>Keep the moments that matter in one private timeline. Your memories stay in this browser until you choose to export or share them.</p><div class="actions"><button class="primary" onclick="document.getElementById(\'fileInput\').click()">＋ Add memories</button><button class="secondary" onclick="mode=\'story\';render()">▶ Replay my year</button></div><input id="fileInput" hidden type="file" accept="image/*" multiple></section><section class="stats"><div><b>'+s.photos+'</b><span>memories</span></div><div><b>'+s.places+'</b><span>places</span></div><div><b>'+s.years+'</b><span>years</span></div><div><b>∞</b><span>stories</span></div></section><section class="tools"><input id="search" placeholder="Search memories…" value="'+esc(query)+'"><select id="place"><option value="all">All places</option>'+places.map(function(p){return '<option value="'+esc(p)+'" '+(p===placeFilter?'selected':'')+'>'+esc(p)+'</option>'}).join('')+'</select><label class="importBtn">Import<input hidden type="file" id="importFile" accept="application/json"></label></section><section class="sectionHead"><div><div class="eyebrow">YOUR TIMELINE</div><h2>Moments that matter</h2></div><button class="add" onclick="document.getElementById(\'fileInput\').click()">＋</button></section><section class="timeline">'+timeline+'</section><section class="cta"><div class="eyebrow">✦ KEEP GOING</div><h2>There are more stories<br>waiting to be remembered.</h2><button class="primary" onclick="document.getElementById(\'fileInput\').click()">Add another memory →</button></section></main></div>';
document.getElementById('fileInput').addEventListener('change',handleFiles);document.getElementById('search').addEventListener('input',function(e){query=e.target.value;renderHome()});document.getElementById('place').addEventListener('change',function(e){placeFilter=e.target.value;renderHome()});document.getElementById('importFile').addEventListener('change',importData)}
function renderStory(){var s=stats(),html='<div class="story"><button class="back" onclick="goHome()">← Back to timeline</button><section class="storyIntro"><div class="eyebrow">✦ YOUR REPLAY</div><h1>One year.<br><em>So many moments.</em></h1><p>'+memories.length+' memories across '+s.places+' places. Here is your story so far.</p><button class="primary" onclick="shareStory()">↗ Share story</button></section><section class="storyGrid">';memories.slice().sort(function(a,b){return b.date.localeCompare(a.date)}).forEach(function(m){html+='<article class="storyItem"><img src="'+esc(m.src)+'" alt="'+esc(m.title)+'" loading="lazy"><div><small>'+fmtDate(m.date)+' · '+esc(m.place)+'</small><h3>'+esc(m.title)+'</h3><p>'+esc(m.caption)+'</p></div></article>'});html+='</section><footer>life replay · your memories, your story.</footer></div>';document.getElementById('app').innerHTML=html}
function handleFiles(e){Array.prototype.forEach.call(e.target.files,function(f,i){if(!f.type||f.type.indexOf('image/')!==0)return;var r=new FileReader();r.onload=function(){memories.unshift({id:Date.now()+i,date:new Date(f.lastModified||Date.now()).toISOString().slice(0,10),title:f.name.replace(/\.[^.]+$/,'').replace(/[-_]+/g,' ')||'A moment worth remembering',caption:'Captured and kept.',place:'My memories',src:r.result,type:f.type});save();render();toast('Memory added to your replay ✦')};r.readAsDataURL(f)});e.target.value=''}
function openMemory(id){var m=memories.filter(function(x){return Number(x.id)===Number(id)})[0];if(!m)return;document.getElementById('app').insertAdjacentHTML('beforeend','<div class="modal" id="modal" onclick="closeModal()"><div class="modalBox" onclick="event.stopPropagation()"><button class="close" onclick="closeModal()">×</button><img src="'+esc(m.src)+'" alt="'+esc(m.title)+'"><div class="modalContent"><small>'+fmtDate(m.date)+' · '+esc(m.place)+'</small><h2>'+esc(m.title)+'</h2><p>'+esc(m.caption)+'</p><button class="danger" onclick="removeMemory('+Number(m.id)+')">Remove memory</button></div></div></div>')}
function closeModal(){var m=document.getElementById('modal');if(m)m.remove()}
function removeMemory(id){memories=memories.filter(function(m){return Number(m.id)!==Number(id)});save();closeModal();render();toast('Memory removed')}
function shareStory(){var clean=memories.map(function(m){return{id:m.id,date:m.date,title:m.title,caption:m.caption,place:m.place}});var payload=btoa(unescape(encodeURIComponent(JSON.stringify(clean))));var url=location.origin+location.pathname+'#replay='+payload;if(navigator.share){navigator.share({title:'My Life Replay',text:'My Life Replay — '+memories.length+' memories across '+stats().places+' places.',url:url}).catch(function(){})}else if(navigator.clipboard){navigator.clipboard.writeText(url).then(function(){toast('Share link copied')}).catch(function(){toast('Use the browser share menu')})}else toast('Share link ready')}
function restoreShared(){var h=location.hash;if(h.indexOf('#replay=')!==0)return;try{var x=JSON.parse(decodeURIComponent(escape(atob(h.slice(8)))));if(Array.isArray(x)&&x.length){memories=x.map(function(m){return Object.assign({},m,{src:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=85'})});mode='story'}}catch(e){}}
function exportData(){var blob=new Blob([JSON.stringify(memories,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='life-replay-memories.json';a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},1000);toast('Backup downloaded')}
function importData(e){var f=e.target.files[0];if(!f)return;var r=new FileReader();r.onload=function(){try{var x=JSON.parse(r.result);if(!Array.isArray(x))throw Error('Invalid');memories=x.filter(function(m){return m&&m.date&&m.src}).map(function(m){return Object.assign({},m,{id:m.id||Date.now()+Math.random()})});save();render();toast('Memories restored')}catch(err){toast('Invalid backup file')}};r.readAsText(f);e.target.value=''}
function toast(t){var x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(function(){x.remove()},2200)}
function showRuntimeError(e){var msg=e&&e.message?e.message:'Unknown startup error';document.getElementById('app').innerHTML='<main style="min-height:100vh;display:grid;place-items:center;padding:24px;background:#09090d;color:#fff;font-family:Arial;text-align:center"><div><h1>Life Replay</h1><p>We hit a startup error. The app has been protected from a blank screen.</p><button onclick="location.reload()" style="padding:12px 20px;border:0;border-radius:10px;cursor:pointer">Refresh</button><p style="opacity:.45;font-size:12px">'+esc(msg)+'</p></div></main>'}
memories=load();restoreShared();render();
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js?v=5').catch(function(){})}
