const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const multer = require('multer');

module.exports = function featureRoutes({ app, db, auth }) {
  const DATA_DIR = process.env.DATA_DIR || path.join(__dirname, 'data');
  const MEDIA_DIR = path.join(DATA_DIR, 'media');
  fs.mkdirSync(MEDIA_DIR, { recursive: true });
  const mediaUpload = multer({
    storage: multer.diskStorage({ destination: (_, __, cb) => cb(null, MEDIA_DIR), filename: (_, f, cb) => cb(null, `${crypto.randomUUID()}${path.extname(f.originalname).toLowerCase()}`) }),
    limits: { fileSize: Number(process.env.MAX_MEDIA_BYTES || 250 * 1024 * 1024) },
    fileFilter: (_, f, cb) => cb(null, /^(image|video|audio|application|text)\//i.test(f.mimetype))
  });

  db.exec(`
    CREATE TABLE IF NOT EXISTS profiles (user_id TEXT PRIMARY KEY, bio TEXT DEFAULT '', avatar_url TEXT DEFAULT '', timezone TEXT DEFAULT 'UTC', privacy TEXT DEFAULT 'private', updated_at TEXT NOT NULL, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
    CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, token_hash TEXT NOT NULL UNIQUE, device TEXT DEFAULT '', created_at TEXT NOT NULL, expires_at TEXT NOT NULL, revoked_at TEXT, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
    CREATE TABLE IF NOT EXISTS memory_meta (memory_id TEXT PRIMARY KEY, time TEXT, timezone TEXT, lat REAL, lng REAL, address TEXT, category TEXT DEFAULT 'memory', mood TEXT, favorite INTEGER DEFAULT 0, pinned INTEGER DEFAULT 0, deleted_at TEXT, source TEXT DEFAULT 'manual', summary TEXT DEFAULT '', weather TEXT, FOREIGN KEY(memory_id) REFERENCES memories(id) ON DELETE CASCADE);
    CREATE TABLE IF NOT EXISTS media (id TEXT PRIMARY KEY, memory_id TEXT, user_id TEXT NOT NULL, original_name TEXT NOT NULL, mime_type TEXT NOT NULL, size INTEGER NOT NULL, storage_path TEXT NOT NULL, checksum TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(memory_id) REFERENCES memories(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
    CREATE TABLE IF NOT EXISTS tags (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, name TEXT NOT NULL, UNIQUE(user_id,name), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
    CREATE TABLE IF NOT EXISTS memory_tags (memory_id TEXT NOT NULL, tag_id TEXT NOT NULL, PRIMARY KEY(memory_id,tag_id), FOREIGN KEY(memory_id) REFERENCES memories(id) ON DELETE CASCADE, FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE);
    CREATE TABLE IF NOT EXISTS people (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, name TEXT NOT NULL, UNIQUE(user_id,name), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
    CREATE TABLE IF NOT EXISTS memory_people (memory_id TEXT NOT NULL, person_id TEXT NOT NULL, PRIMARY KEY(memory_id,person_id), FOREIGN KEY(memory_id) REFERENCES memories(id) ON DELETE CASCADE, FOREIGN KEY(person_id) REFERENCES people(id) ON DELETE CASCADE);
    CREATE TABLE IF NOT EXISTS locations (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, name TEXT NOT NULL, lat REAL, lng REAL, address TEXT, UNIQUE(user_id,name), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
    CREATE TABLE IF NOT EXISTS memory_locations (memory_id TEXT PRIMARY KEY, location_id TEXT NOT NULL, FOREIGN KEY(memory_id) REFERENCES memories(id) ON DELETE CASCADE, FOREIGN KEY(location_id) REFERENCES locations(id) ON DELETE CASCADE);
    CREATE TABLE IF NOT EXISTS shares (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, token TEXT UNIQUE NOT NULL, title TEXT DEFAULT '', visibility TEXT DEFAULT 'private', password_hash TEXT, expires_at TEXT, created_at TEXT NOT NULL, revoked_at TEXT, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
    CREATE TABLE IF NOT EXISTS share_items (share_id TEXT NOT NULL, memory_id TEXT NOT NULL, PRIMARY KEY(share_id,memory_id), FOREIGN KEY(share_id) REFERENCES shares(id) ON DELETE CASCADE, FOREIGN KEY(memory_id) REFERENCES memories(id) ON DELETE CASCADE);
    CREATE TABLE IF NOT EXISTS collaborators (memory_id TEXT NOT NULL, owner_id TEXT NOT NULL, user_email TEXT NOT NULL, role TEXT DEFAULT 'viewer', status TEXT DEFAULT 'invited', created_at TEXT NOT NULL, PRIMARY KEY(memory_id,user_email), FOREIGN KEY(memory_id) REFERENCES memories(id) ON DELETE CASCADE);
    CREATE TABLE IF NOT EXISTS comments (id TEXT PRIMARY KEY, memory_id TEXT NOT NULL, user_id TEXT NOT NULL, body TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(memory_id) REFERENCES memories(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
    CREATE TABLE IF NOT EXISTS reactions (memory_id TEXT NOT NULL, user_id TEXT NOT NULL, reaction TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY(memory_id,user_id), FOREIGN KEY(memory_id) REFERENCES memories(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
    CREATE TABLE IF NOT EXISTS calendar_events (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, title TEXT NOT NULL, start_at TEXT NOT NULL, end_at TEXT, notes TEXT DEFAULT '', memory_id TEXT, created_at TEXT NOT NULL, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
    CREATE TABLE IF NOT EXISTS notifications (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, type TEXT NOT NULL, title TEXT NOT NULL, body TEXT DEFAULT '', read_at TEXT, created_at TEXT NOT NULL, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
    CREATE TABLE IF NOT EXISTS ai_jobs (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, type TEXT NOT NULL, status TEXT DEFAULT 'pending', input_json TEXT, output_json TEXT, error TEXT, created_at TEXT NOT NULL, completed_at TEXT, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
    CREATE TABLE IF NOT EXISTS embeddings (memory_id TEXT PRIMARY KEY, user_id TEXT NOT NULL, text TEXT NOT NULL, vector_json TEXT, created_at TEXT NOT NULL, FOREIGN KEY(memory_id) REFERENCES memories(id) ON DELETE CASCADE);
    CREATE TABLE IF NOT EXISTS replays (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, title TEXT NOT NULL, period_start TEXT, period_end TEXT, status TEXT DEFAULT 'ready', narrative TEXT DEFAULT '', created_at TEXT NOT NULL, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
    CREATE TABLE IF NOT EXISTS audit_logs (id TEXT PRIMARY KEY, user_id TEXT, action TEXT NOT NULL, resource_type TEXT, resource_id TEXT, metadata TEXT, created_at TEXT NOT NULL);
  `);

  const now = () => new Date().toISOString();
  const uid = () => crypto.randomUUID();
  const hash = s => crypto.createHash('sha256').update(s).digest('hex');
  const audit = (u,a,t,id,m={}) => db.prepare('INSERT INTO audit_logs VALUES (?,?,?,?,?,?,?)').run(uid(),u,a,t||null,id||null,JSON.stringify(m),now());
  const owned = (id,u) => db.prepare('SELECT m.*, COALESCE(mm.favorite,0) favorite, COALESCE(mm.pinned,0) pinned, mm.time,mm.timezone,mm.lat,mm.lng,mm.address,mm.category,mm.mood,mm.summary,mm.weather,mm.deleted_at,mm.source FROM memories m LEFT JOIN memory_meta mm ON mm.memory_id=m.id WHERE m.id=? AND m.user_id=?').get(id,u);
  const enrich = (m,u) => m && ({...m, favorite:!!m.favorite,pinned:!!m.pinned,tags:db.prepare('SELECT t.name FROM tags t JOIN memory_tags mt ON mt.tag_id=t.id WHERE mt.memory_id=?').all(m.id).map(x=>x.name),people:db.prepare('SELECT p.name FROM people p JOIN memory_people mp ON mp.person_id=p.id WHERE mp.memory_id=?').all(m.id).map(x=>x.name),media:db.prepare('SELECT id,original_name originalName,mime_type mimeType,size,checksum,storage_path storagePath,created_at createdAt FROM media WHERE memory_id=?').all(m.id)});

  app.get('/api/v1/profile', auth, (req,res)=>{ let p=db.prepare('SELECT * FROM profiles WHERE user_id=?').get(req.user.id); if(!p){db.prepare('INSERT INTO profiles(user_id,updated_at) VALUES(?,?)').run(req.user.id,now());p=db.prepare('SELECT * FROM profiles WHERE user_id=?').get(req.user.id)} res.json({profile:p,user:{id:req.user.id,email:req.user.email,name:req.user.name,createdAt:req.user.created_at}}); });
  app.patch('/api/v1/profile', auth, (req,res)=>{ const b=req.body||{}; db.prepare(`INSERT INTO profiles(user_id,bio,avatar_url,timezone,privacy,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET bio=excluded.bio,avatar_url=excluded.avatar_url,timezone=excluded.timezone,privacy=excluded.privacy,updated_at=excluded.updated_at`).run(req.user.id,String(b.bio||''),String(b.avatarUrl||''),String(b.timezone||'UTC'),['private','shared','public'].includes(b.privacy)?b.privacy:'private',now()); res.json({profile:db.prepare('SELECT * FROM profiles WHERE user_id=?').get(req.user.id)}); });

  app.post('/api/v1/auth/refresh', auth, (req,res)=>{ const raw=crypto.randomBytes(48).toString('base64url'), exp=new Date(Date.now()+30*864e5).toISOString(); db.prepare('INSERT INTO sessions VALUES(?,?,?,?,?,?,?)').run(uid(),req.user.id,hash(raw),req.headers['user-agent']||'',now(),exp,null); res.json({refreshToken:raw,expiresAt:exp}); });
  app.post('/api/v1/auth/logout-all', auth, (req,res)=>{db.prepare('UPDATE sessions SET revoked_at=? WHERE user_id=?').run(now(),req.user.id);res.status(204).end()});
  app.get('/api/v1/sessions', auth, (req,res)=>res.json({sessions:db.prepare('SELECT id,device,created_at createdAt,expires_at expiresAt,revoked_at revokedAt FROM sessions WHERE user_id=? ORDER BY created_at DESC').all(req.user.id)}));
  app.delete('/api/v1/sessions/:id', auth, (req,res)=>{db.prepare('UPDATE sessions SET revoked_at=? WHERE id=? AND user_id=?').run(now(),req.params.id,req.user.id);res.status(204).end()});

  app.get('/api/v1/memories', auth, (req,res)=>{ const q=String(req.query.q||'').trim().toLowerCase(), from=req.query.from||'', to=req.query.to||'', person=req.query.person||'', place=req.query.place||'', category=req.query.category||'', tag=req.query.tag||'', favorite=req.query.favorite, includeTrash=req.query.trash==='true'; let sql=`SELECT m.*,COALESCE(mm.favorite,0) favorite,COALESCE(mm.pinned,0) pinned,mm.time,mm.timezone,mm.lat,mm.lng,mm.address,mm.category,mm.mood,mm.summary,mm.weather,mm.deleted_at,mm.source FROM memories m LEFT JOIN memory_meta mm ON mm.memory_id=m.id WHERE m.user_id=?`; const a=[req.user.id]; if(!includeTrash)sql+=' AND mm.deleted_at IS NULL';if(q){sql+=' AND lower(m.title||\' \u005c\'||m.caption||\' \u005c\'||m.place||\' \u005c\'||COALESCE(mm.summary,\'\')) LIKE ?';a.push('%'+q+'%')}if(from){sql+=' AND m.date>=?';a.push(from)}if(to){sql+=' AND m.date<=?';a.push(to)}if(place){sql+=' AND lower(m.place)=lower(?)';a.push(place)}if(category){sql+=' AND mm.category=?';a.push(category)}if(favorite==='true')sql+=' AND mm.favorite=1';sql+=' ORDER BY m.date DESC,m.created_at DESC';let rows=db.prepare(sql).all(...a).map(x=>enrich(x,req.user.id));if(person)rows=rows.filter(x=>x.people.some(p=>p.toLowerCase()===String(person).toLowerCase()));if(tag)rows=rows.filter(x=>x.tags.some(t=>t.toLowerCase()===String(tag).toLowerCase()));res.json({memories:rows}); });

  app.post('/api/v1/memories', auth, (req,res)=>{ const b=req.body||{}, id=uid(), created=now(), date=/^\d{4}-\d{2}-\d{2}$/.test(b.date||'')?b.date:created.slice(0,10); if(!String(b.title||'').trim())return res.status(400).json({error:'title is required'}); db.prepare('INSERT INTO memories VALUES(?,?,?,?,?,?,?,?)').run(id,req.user.id,String(b.title).slice(0,200),String(b.caption||''),String(b.place||''),date,String(b.mediaUrl||''),created);db.prepare('INSERT INTO memory_meta(memory_id,time,timezone,lat,lng,address,category,mood,source,summary,weather) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,b.time||null,b.timezone||'UTC',b.lat??null,b.lng??null,b.address||null,b.category||'memory',b.mood||null,b.source||'manual',b.summary||'',b.weather||null);syncLists(id,req.user.id,b);audit(req.user.id,'memory.create','memory',id);res.status(201).json({memory:enrich(owned(id,req.user.id),req.user.id)}); });
  app.patch('/api/v1/memories/:id', auth, (req,res)=>{const m=owned(req.params.id,req.user.id);if(!m)return res.status(404).json({error:'Memory not found'});const b=req.body||{};db.prepare('UPDATE memories SET title=COALESCE(?,title),caption=COALESCE(?,caption),place=COALESCE(?,place),date=COALESCE(?,date),media_url=COALESCE(?,media_url) WHERE id=? AND user_id=?').run(b.title??null,b.caption??null,b.place??null,b.date??null,b.mediaUrl??null,m.id,req.user.id);db.prepare(`INSERT INTO memory_meta(memory_id,time,timezone,lat,lng,address,category,mood,favorite,pinned,source,summary,weather) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(memory_id) DO UPDATE SET time=COALESCE(excluded.time,time),timezone=COALESCE(excluded.timezone,timezone),lat=COALESCE(excluded.lat,lat),lng=COALESCE(excluded.lng,lng),address=COALESCE(excluded.address,address),category=COALESCE(excluded.category,category),mood=COALESCE(excluded.mood,mood),favorite=COALESCE(excluded.favorite,favorite),pinned=COALESCE(excluded.pinned,pinned),source=COALESCE(excluded.source,source),summary=COALESCE(excluded.summary,summary),weather=COALESCE(excluded.weather,weather)`).run(m.id,b.time??null,b.timezone??null,b.lat??null,b.lng??null,b.address??null,b.category??null,b.mood??null,b.favorite==null?null:+!!b.favorite,b.pinned==null?null:+!!b.pinned,b.source??null,b.summary??null,b.weather??null);syncLists(m.id,req.user.id,b);audit(req.user.id,'memory.update','memory',m.id);res.json({memory:enrich(owned(m.id,req.user.id),req.user.id)}); });
  app.delete('/api/v1/memories/:id',auth,(req,res)=>{const m=owned(req.params.id,req.user.id);if(!m)return res.status(404).json({error:'Memory not found'});db.prepare('INSERT INTO memory_meta(memory_id,deleted_at) VALUES(?,?) ON CONFLICT(memory_id) DO UPDATE SET deleted_at=excluded.deleted_at').run(m.id,now());audit(req.user.id,'memory.trash','memory',m.id);res.status(204).end()});
  app.post('/api/v1/memories/:id/restore',auth,(req,res)=>{if(!owned(req.params.id,req.user.id))return res.status(404).json({error:'Memory not found'});db.prepare('UPDATE memory_meta SET deleted_at=NULL WHERE memory_id=?').run(req.params.id);res.json({ok:true,memory:enrich(owned(req.params.id,req.user.id),req.user.id)})});
  app.delete('/api/v1/memories/:id/permanent',auth,(req,res)=>{const m=owned(req.params.id,req.user.id);if(!m)return res.status(404).json({error:'Memory not found'});db.prepare('DELETE FROM memories WHERE id=? AND user_id=?').run(m.id,req.user.id);res.status(204).end()});
  app.post('/api/v1/memories/:id/favorite',auth,(req,res)=>toggleMeta(req,res,'favorite'));
  app.post('/api/v1/memories/:id/pin',auth,(req,res)=>toggleMeta(req,res,'pinned'));

  app.post('/api/v1/memories/:id/media',auth,mediaUpload.array('files',20),(req,res)=>{const m=owned(req.params.id,req.user.id);if(!m)return res.status(404).json({error:'Memory not found'});const out=[];for(const f of req.files||[]){const sum=hash(fs.readFileSync(f.path));const duplicate=db.prepare('SELECT * FROM media WHERE user_id=? AND checksum=?').get(req.user.id,sum);if(duplicate){fs.unlinkSync(f.path);continue}const x={id:uid(),memory_id:m.id,user_id:req.user.id,original_name:f.originalname,mime_type:f.mimetype,size:f.size,storage_path:f.path,checksum:sum,created_at:now()};db.prepare('INSERT INTO media VALUES(?,?,?,?,?,?,?,?,?)').run(...Object.values(x));out.push(x)}res.status(201).json({media:out})});
  app.get('/api/v1/media/:id',auth,(req,res)=>{const m=db.prepare('SELECT * FROM media WHERE id=? AND user_id=?').get(req.params.id,req.user.id);if(!m)return res.status(404).end();res.sendFile(path.resolve(m.storage_path))});
  app.delete('/api/v1/media/:id',auth,(req,res)=>{const m=db.prepare('SELECT * FROM media WHERE id=? AND user_id=?').get(req.params.id,req.user.id);if(!m)return res.status(404).end();db.prepare('DELETE FROM media WHERE id=?').run(m.id);if(fs.existsSync(m.storage_path))fs.unlinkSync(m.storage_path);res.status(204).end()});

  app.get('/api/v1/timeline',auth,(req,res)=>{const rows=db.prepare(`SELECT m.date,COUNT(*) count,GROUP_CONCAT(m.id) memoryIds FROM memories m LEFT JOIN memory_meta mm ON mm.memory_id=m.id WHERE m.user_id=? AND mm.deleted_at IS NULL GROUP BY m.date ORDER BY m.date DESC`).all(req.user.id).map(r=>({...r,memoryIds:r.memoryIds?r.memoryIds.split(','):[]}));res.json({timeline:rows})});
  app.get('/api/v1/calendar',auth,(req,res)=>res.json({events:db.prepare('SELECT * FROM calendar_events WHERE user_id=? ORDER BY start_at').all(req.user.id)}));
  app.post('/api/v1/calendar',auth,(req,res)=>{const b=req.body||{};if(!b.title||!b.startAt)return res.status(400).json({error:'title and startAt required'});const e={id:uid(),user_id:req.user.id,title:b.title,start_at:b.startAt,end_at:b.endAt||null,notes:b.notes||'',memory_id:b.memoryId||null,created_at:now()};db.prepare('INSERT INTO calendar_events VALUES(?,?,?,?,?,?,?)').run(...Object.values(e));res.status(201).json({event:e})});
  app.delete('/api/v1/calendar/:id',auth,(req,res)=>{db.prepare('DELETE FROM calendar_events WHERE id=? AND user_id=?').run(req.params.id,req.user.id);res.status(204).end()});

  app.get('/api/v1/tags',auth,(req,res)=>res.json({tags:db.prepare('SELECT id,name FROM tags WHERE user_id=? ORDER BY name').all(req.user.id)}));
  app.get('/api/v1/people',auth,(req,res)=>res.json({people:db.prepare('SELECT id,name FROM people WHERE user_id=? ORDER BY name').all(req.user.id)}));
  app.get('/api/v1/locations',auth,(req,res)=>res.json({locations:db.prepare('SELECT * FROM locations WHERE user_id=? ORDER BY name').all(req.user.id)}));

  app.get('/api/v1/on-this-day',auth,(req,res)=>{const md=new Date().toISOString().slice(5,10);res.json({memories:db.prepare(`SELECT m.* FROM memories m LEFT JOIN memory_meta mm ON mm.memory_id=m.id WHERE m.user_id=? AND substr(m.date,6,5)=? AND mm.deleted_at IS NULL ORDER BY m.date DESC`).all(req.user.id,md).map(m=>enrich(owned(m.id,req.user.id),req.user.id))})});
  app.get('/api/v1/stats',auth,(req,res)=>{const total=db.prepare('SELECT COUNT(*) n FROM memories WHERE user_id=?').get(req.user.id).n,years=db.prepare('SELECT COUNT(DISTINCT substr(date,1,4)) n FROM memories WHERE user_id=?').get(req.user.id).n,places=db.prepare('SELECT COUNT(DISTINCT place) n FROM memories WHERE user_id=? AND place<>\'\'').get(req.user.id).n;res.json({memories:total,yearsCaptured:years,places,media:db.prepare('SELECT COUNT(*) n FROM media WHERE user_id=?').get(req.user.id).n})});

  app.post('/api/v1/shares',auth,(req,res)=>{const b=req.body||{}, ids=Array.isArray(b.memoryIds)?b.memoryIds:db.prepare('SELECT id FROM memories WHERE user_id=? AND (SELECT deleted_at FROM memory_meta WHERE memory_id=memories.id) IS NULL').all(req.user.id).map(x=>x.id);if(!ids.length)return res.status(400).json({error:'No memories selected'});const valid=ids.filter(id=>owned(id,req.user.id));const token=crypto.randomBytes(32).toString('base64url'),id=uid();db.prepare('INSERT INTO shares VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,req.user.id,token,b.title||'Life Replay',b.visibility||'private',null,b.expiresAt||null,now(),null);const ins=db.prepare('INSERT INTO share_items VALUES(?,?)');db.transaction(()=>valid.forEach(x=>ins.run(id,x)))();res.status(201).json({share:{id,token,url:`${req.protocol}://${req.get('host')}/share/${token}`,memoryIds:valid}})});
  app.get('/api/v1/shares',auth,(req,res)=>res.json({shares:db.prepare('SELECT id,token,title,visibility,expires_at expiresAt,created_at createdAt,revoked_at revokedAt FROM shares WHERE user_id=? ORDER BY created_at DESC').all(req.user.id)}));
  app.delete('/api/v1/shares/:id',auth,(req,res)=>{db.prepare('UPDATE shares SET revoked_at=? WHERE id=? AND user_id=?').run(now(),req.params.id,req.user.id);res.status(204).end()});
  app.get('/api/v1/share/:token',(req,res)=>{const s=db.prepare('SELECT * FROM shares WHERE token=? AND revoked_at IS NULL').get(req.params.token);if(!s||(s.expires_at&&new Date(s.expires_at)<new Date()))return res.status(404).json({error:'Share not found or expired'});const owner=db.prepare('SELECT id,name FROM users WHERE id=?').get(s.user_id),ids=db.prepare('SELECT memory_id FROM share_items WHERE share_id=?').all(s.id).map(x=>x.memory_id);res.json({owner,share:{id:s.id,title:s.title,visibility:s.visibility},memories:ids.map(id=>enrich(owned(id,s.user_id),s.user_id)).filter(Boolean)});});

  app.post('/api/v1/memories/:id/collaborators',auth,(req,res)=>{if(!owned(req.params.id,req.user.id))return res.status(404).json({error:'Memory not found'});const email=String(req.body?.email||'').toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))return res.status(400).json({error:'Valid email required'});db.prepare('INSERT OR REPLACE INTO collaborators VALUES(?,?,?,?,?,?)').run(req.params.id,req.user.id,email,['viewer','contributor'].includes(req.body?.role)?req.body.role:'viewer','invited',now());res.status(201).json({ok:true,email,role:req.body?.role||'viewer'})});
  app.get('/api/v1/memories/:id/collaborators',auth,(req,res)=>{if(!owned(req.params.id,req.user.id))return res.status(404).end();res.json({collaborators:db.prepare('SELECT user_email email,role,status,created_at createdAt FROM collaborators WHERE memory_id=? AND owner_id=?').all(req.params.id,req.user.id)})});
  app.delete('/api/v1/memories/:id/collaborators/:email',auth,(req,res)=>{if(!owned(req.params.id,req.user.id))return res.status(404).end();db.prepare('DELETE FROM collaborators WHERE memory_id=? AND owner_id=? AND user_email=?').run(req.params.id,req.user.id,decodeURIComponent(req.params.email).toLowerCase());res.status(204).end()});
  app.get('/api/v1/memories/:id/comments',auth,(req,res)=>{if(!owned(req.params.id,req.user.id))return res.status(404).end();res.json({comments:db.prepare('SELECT c.*,u.name FROM comments c JOIN users u ON u.id=c.user_id WHERE c.memory_id=? ORDER BY c.created_at').all(req.params.id)})});
  app.post('/api/v1/memories/:id/comments',auth,(req,res)=>{if(!owned(req.params.id,req.user.id))return res.status(404).end();const body=String(req.body?.body||'').trim();if(!body)return res.status(400).json({error:'Comment required'});const c={id:uid(),memory_id:req.params.id,user_id:req.user.id,body,created_at:now()};db.prepare('INSERT INTO comments VALUES(?,?,?,?,?)').run(...Object.values(c));res.status(201).json({comment:c})});
  app.delete('/api/v1/comments/:id',auth,(req,res)=>{db.prepare('DELETE FROM comments WHERE id=? AND user_id=?').run(req.params.id,req.user.id);res.status(204).end()});
  app.post('/api/v1/memories/:id/reaction',auth,(req,res)=>{if(!owned(req.params.id,req.user.id))return res.status(404).end();const reaction=String(req.body?.reaction||'❤️').slice(0,20);db.prepare('INSERT INTO reactions VALUES(?,?,?,?) ON CONFLICT(memory_id,user_id) DO UPDATE SET reaction=excluded.reaction,created_at=excluded.created_at').run(req.params.id,req.user.id,reaction,now());res.json({ok:true,reaction})});

  app.get('/api/v1/notifications',auth,(req,res)=>res.json({notifications:db.prepare('SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 100').all(req.user.id)}));
  app.post('/api/v1/notifications/:id/read',auth,(req,res)=>{db.prepare('UPDATE notifications SET read_at=? WHERE id=? AND user_id=?').run(now(),req.params.id,req.user.id);res.status(204).end()});

  app.post('/api/v1/ai/ask',auth,async(req,res)=>{const question=String(req.body?.question||'').trim();if(!question)return res.status(400).json({error:'question required'});const memories=db.prepare(`SELECT m.* FROM memories m LEFT JOIN memory_meta mm ON mm.memory_id=m.id WHERE m.user_id=? AND mm.deleted_at IS NULL ORDER BY m.date DESC LIMIT 500`).all(req.user.id).map(m=>enrich(owned(m.id,req.user.id),req.user.id));const context=memories.map(m=>`${m.date} | ${m.title} | ${m.place} | ${m.caption} | ${m.summary||''} | ${m.people.join(',')} | ${m.tags.join(',')}`).join('\n');let answer=localAnswer(question,memories);if(process.env.OPENAI_API_KEY){try{const r=await fetch(process.env.OPENAI_BASE_URL||'https://api.openai.com/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-4o-mini',temperature:.2,messages:[{role:'system',content:'You are Life Replay. Answer only from the supplied user memory data. If the data does not contain the answer, say so. Never invent personal events.'},{role:'user',content:`Question: ${question}\nMEMORIES:\n${context}`}]})});const d=await r.json();if(r.ok)answer=d.choices?.[0]?.message?.content||answer}catch{}}const job={id:uid(),user_id:req.user.id,type:'ask',status:'completed',input_json:JSON.stringify({question}),output_json:JSON.stringify({answer}),error:null,created_at:now(),completed_at:now()};db.prepare('INSERT INTO ai_jobs VALUES(?,?,?,?,?,?,?,?,?)').run(...Object.values(job));res.json({answer,matches:memories.filter(m=>(m.title+' '+m.caption+' '+m.place+' '+m.date+' '+m.people.join(' ')+' '+m.tags.join(' ')).toLowerCase().includes(question.toLowerCase())).slice(0,20)})});
  app.post('/api/v1/ai/summarize/:id',auth,async(req,res)=>{const m=owned(req.params.id,req.user.id);if(!m)return res.status(404).end();const summary=`${m.title}. ${m.caption}${m.place?` Recorded at ${m.place}.`:''}`.slice(0,500);db.prepare('UPDATE memory_meta SET summary=? WHERE memory_id=?').run(summary,m.id);res.json({summary,memory:enrich(owned(m.id,req.user.id),req.user.id)})});

  app.post('/api/v1/replays',auth,(req,res)=>{const b=req.body||{},start=b.startDate||'0000-01-01',end=b.endDate||'9999-12-31',ms=db.prepare('SELECT * FROM memories WHERE user_id=? AND date BETWEEN ? AND ? ORDER BY date').all(req.user.id,start,end).map(x=>enrich(owned(x.id,req.user.id),req.user.id));const narrative=ms.map(m=>`${m.date}: ${m.title}${m.place?` — ${m.place}`:''}. ${m.caption}`).join('\n');const r={id:uid(),user_id:req.user.id,title:b.title||'Life Replay',period_start:b.startDate||null,period_end:b.endDate||null,status:'ready',narrative,created_at:now()};db.prepare('INSERT INTO replays VALUES(?,?,?,?,?,?,?,?)').run(...Object.values(r));res.status(201).json({replay:r,memories:ms})});
  app.get('/api/v1/replays',auth,(req,res)=>res.json({replays:db.prepare('SELECT * FROM replays WHERE user_id=? ORDER BY created_at DESC').all(req.user.id)}));
  app.get('/api/v1/replays/:id',auth,(req,res)=>{const r=db.prepare('SELECT * FROM replays WHERE id=? AND user_id=?').get(req.params.id,req.user.id);if(!r)return res.status(404).end();res.json({replay:r})});

  app.post('/api/v1/imports/google-photos',auth,(req,res)=>res.status(202).json({status:'ready_for_oauth',provider:'google-photos',message:'Configure GOOGLE_CLIENT_ID/GOOGLE_CLIENT_SECRET and callback credentials to enable OAuth import.'}));
  app.post('/api/v1/imports/apple-photos',auth,(req,res)=>res.status(202).json({status:'provider-dependent',provider:'apple-photos',message:'Apple Photos import requires a supported user-authorized Photos/library integration.'}));
  app.get('/api/v1/imports',auth,(req,res)=>res.json({imports:db.prepare('SELECT * FROM ai_jobs WHERE user_id=? AND type LIKE \'import:%\' ORDER BY created_at DESC').all(req.user.id)}));

  app.get('/api/v1/export',auth,(req,res)=>{const u={id:req.user.id,email:req.user.email,name:req.user.name,profile:db.prepare('SELECT * FROM profiles WHERE user_id=?').get(req.user.id),memories:db.prepare('SELECT * FROM memories WHERE user_id=?').all(req.user.id).map(m=>enrich(owned(m.id,req.user.id),req.user.id)),calendar:db.prepare('SELECT * FROM calendar_events WHERE user_id=?').all(req.user.id),shares:db.prepare('SELECT id,title,visibility,expires_at,created_at FROM shares WHERE user_id=?').all(req.user.id)};res.setHeader('Content-Disposition','attachment; filename="life-replay-export.json"');res.json(u)});
  app.delete('/api/v1/account',auth,(req,res)=>{const id=req.user.id;db.prepare('DELETE FROM users WHERE id=?').run(id);res.status(204).end()});
  app.get('/api/v1/audit',auth,(req,res)=>res.json({events:db.prepare('SELECT action,resource_type resourceType,resource_id resourceId,metadata,created_at createdAt FROM audit_logs WHERE user_id=? ORDER BY created_at DESC LIMIT 500').all(req.user.id)}));
  app.get('/api/v1/readiness',auth,(req,res)=>res.json({ok:true,database:'sqlite',storage:fs.existsSync(MEDIA_DIR),ai:!!process.env.OPENAI_API_KEY,version:'1.0.0'}));

  function syncLists(memoryId,userId,b){
    if(Array.isArray(b.tags)){db.prepare('DELETE FROM memory_tags WHERE memory_id=?').run(memoryId);for(const name of b.tags.map(String).map(x=>x.trim()).filter(Boolean)){let t=db.prepare('SELECT id FROM tags WHERE user_id=? AND name=?').get(userId,name);if(!t){t={id:uid()};db.prepare('INSERT INTO tags VALUES(?,?,?)').run(t.id,userId,name)}db.prepare('INSERT OR IGNORE INTO memory_tags VALUES(?,?)').run(memoryId,t.id)}}
    if(Array.isArray(b.people)){db.prepare('DELETE FROM memory_people WHERE memory_id=?').run(memoryId);for(const name of b.people.map(String).map(x=>x.trim()).filter(Boolean)){let p=db.prepare('SELECT id FROM people WHERE user_id=? AND name=?').get(userId,name);if(!p){p={id:uid()};db.prepare('INSERT INTO people VALUES(?,?,?)').run(p.id,userId,name)}db.prepare('INSERT OR IGNORE INTO memory_people VALUES(?,?)').run(memoryId,p.id)}}
    if(b.locationName){let l=db.prepare('SELECT id FROM locations WHERE user_id=? AND name=?').get(userId,b.locationName);if(!l){l={id:uid()};db.prepare('INSERT INTO locations VALUES(?,?,?,?,?)').run(l.id,userId,b.locationName,b.lat??null,b.lng??null,b.address||null)}db.prepare('INSERT OR REPLACE INTO memory_locations VALUES(?,?)').run(memoryId,l.id)}
  }
  function toggleMeta(req,res,col){const m=owned(req.params.id,req.user.id);if(!m)return res.status(404).json({error:'Memory not found'});const v=req.body?.value==null?!m[col]:!!req.body.value;db.prepare(`INSERT INTO memory_meta(memory_id,${col}) VALUES(?,?) ON CONFLICT(memory_id) DO UPDATE SET ${col}=excluded.${col}`).run(m.id,+v);res.json({ok:true,[col]:v})}
  function localAnswer(q,ms){const l=q.toLowerCase();let x=ms.filter(m=>(m.title+' '+m.caption+' '+m.place+' '+m.date+' '+m.people.join(' ')+' '+m.tags.join(' ')).toLowerCase().includes(l));if(!x.length){const terms=l.split(/\s+/).filter(t=>t.length>2);x=ms.filter(m=>terms.some(t=>(m.title+' '+m.caption+' '+m.place+' '+m.date+' '+m.people.join(' ')+' '+m.tags.join(' ')).toLowerCase().includes(t))).slice(0,10)}return x.length?`I found ${x.length} matching memory${x.length===1?'':'ies'}. ${x.slice(0,5).map(m=>`${m.date}: ${m.title}${m.place?` (${m.place})`:''}`).join(' | ')}`:`I couldn't find a matching memory in your Life Replay data.`}
};